name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Hugging Face Hub
        run: pip install huggingface_hub

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN}}
        run: |
          python - << "EOF"
          import os
          from huggingface_hub import HfApi

          # Hugging Face Space path
          repo_id = "yashuchouhan/Extractive_Text_Summarization_App"

          api = HfApi()

          # Read token from environment (correct way!)
          token = os.environ["HF_TOKEN"]

          # Create space if missing
          api.create_repo(
              repo_id=repo_id,
              repo_type="space",
              exist_ok=True,
              space_sdk="gradio",
              token=token
          )

          # Upload project files
          api.upload_folder(
              folder_path=".",
              repo_id=repo_id,
              repo_type="space",
              ignore_patterns=[".git", ".github"],
              token=token
          )
          EOF